namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests
{
    internal static class AlsoNotifyAttributes
    {
        public static List<(string source, string? expected)> Sources =
        [
            (
                source : """
                         using Minimal.Mvvm;

                         public partial class PersonModel : BindableBase
                         {
                            [Notify, AlsoNotify(nameof(FullName))]
                            private string? _name;

                            [Notify, AlsoNotify(nameof(FullName))]
                            private string? _surname;

                            [Notify, AlsoNotify(nameof(FullName))]
                            private string? _middleName;

                            public string FullName => $"{Surname} {Name} {MiddleName}";
                         }
                         """,
                expected : """
                            // <auto-generated>
                            //     Auto-generated by [GeneratorName] [GeneratorVersion]
                            // </auto-generated>

                            #nullable enable

                            partial class PersonModel
                            {
                                public string? Name
                                {
                                    get => _name;
                                    set
                                    {
                                        if (SetProperty(ref _name, value))
                                        {
                                            RaisePropertyChanged("FullName");
                                        }
                                    }
                                }
                           
                                public string? Surname
                                {
                                    get => _surname;
                                    set
                                    {
                                        if (SetProperty(ref _surname, value))
                                        {
                                            RaisePropertyChanged("FullName");
                                        }
                                    }
                                }

                                public string? MiddleName
                                {
                                    get => _middleName;
                                    set
                                    {
                                        if (SetProperty(ref _middleName, value))
                                        {
                                            RaisePropertyChanged("FullName");
                                        }
                                    }
                                }
                            }
                            """ ),
               (
                source : """
                         using Minimal.Mvvm;
                         using System;

                         public partial class PersonModel : BindableBase
                         {
                            [Notify]
                            [AlsoNotify(nameof(Age), nameof(YearsToRetirement))]
                            private DateTime _birthDate;

                            public int Age => DateTime.Now.Year - BirthDate.Year;

                            public int YearsToRetirement => 65 - Age;
                         }
                         """,
                expected : """
                            // <auto-generated>
                            //     Auto-generated by [GeneratorName] [GeneratorVersion]
                            // </auto-generated>

                            #nullable enable

                            partial class PersonModel
                            {
                                public global::System.DateTime BirthDate
                                {
                                    get => _birthDate;
                                    set
                                    {
                                        if (SetProperty(ref _birthDate, value))
                                        {
                                            RaisePropertiesChanged("Age", "YearsToRetirement");
                                        }
                                    }
                                }
                            }
                            """ ),
            (
                source : """
                         using Minimal.Mvvm;

                         public partial class PersonModel : BindableBase
                         {
                            [Notify]
                            [AlsoNotify(nameof(Taxes), nameof(NetSalary), nameof(AnnualSalary))]
                            private decimal _salary;

                            [Notify]
                            [AlsoNotify(nameof(Taxes))]
                            [AlsoNotify(nameof(NetSalary))]
                            [AlsoNotify(nameof(AnnualSalary))]
                            private decimal _taxRate = 0.2m; 
                         
                            public decimal Taxes => Salary * TaxRate;
                         
                            public decimal NetSalary => Salary - Taxes;

                            public decimal AnnualSalary => NetSalary * 12; 
                         }
                         """,
                expected : """
                           // <auto-generated>
                           //     Auto-generated by [GeneratorName] [GeneratorVersion]
                           // </auto-generated>

                           #nullable enable

                           partial class PersonModel
                           {
                               public decimal Salary
                               {
                                   get => _salary;
                                   set
                                   {
                                       if (SetProperty(ref _salary, value))
                                       {
                                           RaisePropertiesChanged("Taxes", "NetSalary", "AnnualSalary");
                                       }
                                   }
                               }
                           
                               public decimal TaxRate
                               {
                                   get => _taxRate;
                                   set
                                   {
                                       if (SetProperty(ref _taxRate, value))
                                       {
                                           RaisePropertiesChanged("Taxes", "NetSalary", "AnnualSalary");
                                       }
                                   }
                               }
                           }
                           """ ),
            (
                source : """
                         using Minimal.Mvvm;
                         using System;

                         public partial class PersonModel : BindableBase
                         {
                            [Notify(CallbackName = nameof(OnSalaryChanged))]
                            [AlsoNotify]
                            [AlsoNotify("")]
                            [AlsoNotify(nameof(Taxes), nameof(NetSalary), nameof(AnnualSalary))]
                            private decimal _salary;
                         
                            [AlsoNotify]
                            [AlsoNotify("")]
                            [Notify(CallbackName = nameof(OnTaxRateChanged))]
                            [AlsoNotify(nameof(Taxes))]
                            [AlsoNotify(nameof(NetSalary))]
                            [AlsoNotify(nameof(Taxes), nameof(NetSalary), nameof(AnnualSalary))]
                            [AlsoNotify(nameof(AnnualSalary))]
                            private decimal _taxRate = 0.2m; 
                         
                            public decimal Taxes => Salary * TaxRate;
                         
                            public decimal NetSalary => Salary - Taxes;
                         
                            public decimal AnnualSalary => NetSalary * 12;

                            private void OnSalaryChanged(decimal oldSalary)
                            {
                                Console.WriteLine($"Salary changed from {oldSalary} to {Salary}");
                            }

                            private void OnTaxRateChanged()
                            {
                                Console.WriteLine($"New TaxRate: {TaxRate}");
                            }
                         }
                         """,
                expected : """
                           // <auto-generated>
                           //     Auto-generated by [GeneratorName] [GeneratorVersion]
                           // </auto-generated>

                           #nullable enable

                           partial class PersonModel
                           {
                               private global::System.Action<decimal>? _salaryChangedCallback;
                               public decimal Salary
                               {
                                   get => _salary;
                                   set
                                   {
                                       if (SetProperty(ref _salary, value, _salaryChangedCallback ??= OnSalaryChanged))
                                       {
                                           RaisePropertiesChanged("Taxes", "NetSalary", "AnnualSalary");
                                       }
                                   }
                               }

                               private global::System.Action? _taxRateChangedCallback;
                               public decimal TaxRate
                               {
                                   get => _taxRate;
                                   set
                                   {
                                       if (SetProperty(ref _taxRate, value, _taxRateChangedCallback ??= OnTaxRateChanged))
                                       {
                                           RaisePropertiesChanged("Taxes", "NetSalary", "AnnualSalary");
                                       }
                                   }
                               }
                           }
                           """ ),
        ];
    }
}
